### ISSUE TITLE
This only allows the user to click on the very text of an item... Since the user sees a bar, they surely wants to click anywhere on the bar…

### ISSUE THREAD

**Issue by davidcechak** [KenticoAcademy/kentico-onboarding-js#166]
This only allows the user to click on the very text of an item... Since the user sees a bar, they surely wants to click anywhere on the bar…

_Originally posted by @PetrSvirak in https://github.com/_render_node/MDIzOlB1bGxSZXF1ZXN0UmV2aWV3VGhyZWFkMTM1MTE4NDc5OnYy/pull_request_review_threads/discussion_

**Comment by PetrSvirak** [comment]
What? 😆
